import { palette as p } from '../../shared/palette'

// Workbench UI colors.
export const workbench: Record<string, string> = {
  // Core editor.
  'editor.background': p.vscode.bg,
  'editor.foreground': p.base.text,
  'editor.lineHighlightBackground': p.vscode.caretRow,
  'editor.lineHighlightBorder': '#00000000',
  'editor.selectionBackground': p.ui.selection,
  'editor.inactiveSelectionBackground': p.ui.selection + '80',
  'editor.selectionHighlightBackground': p.ui.selection + '50',
  'editor.wordHighlightBackground': p.blue.mid + '20',
  'editor.wordHighlightStrongBackground': p.blue.mid + '40',
  'editor.findMatchBackground': p.violet.mid + '40',
  'editor.findMatchHighlightBackground': p.sand.mid + '30',
  'editor.findMatchBorder': p.violet.mid,
  'editor.findRangeHighlightBackground': p.ui.selection + '40',
  'editor.rangeHighlightBackground': p.blue.mid + '10',
  'editor.symbolHighlightBackground': p.blue.mid + '20',

  // Cursor and line numbers.
  'editorCursor.foreground': p.base.text,
  'editorCursor.background': p.vscode.bg,
  'editorLineNumber.foreground': p.base.inlayHint,
  'editorLineNumber.activeForeground': p.base.chromeMid,

  // Whitespace and indent guides.
  'editorWhitespace.foreground': p.base.inlayHint,
  'editorIndentGuide.background1': p.base.chromeDim,
  'editorIndentGuide.activeBackground1': p.blue.bright,
  'editorRuler.foreground': p.base.chromeDim,

  // Bracket pair colorization.
  'editorBracketHighlight.foreground1': p.blue.mid,
  'editorBracketHighlight.foreground2': p.violet.mid,
  'editorBracketHighlight.foreground3': p.teal.mid,
  'editorBracketHighlight.foreground4': p.green.mid,
  'editorBracketHighlight.foreground5': p.sand.mid,
  'editorBracketHighlight.foreground6': p.orange,
  'editorBracketHighlight.unexpectedBracket.foreground': p.diag.error,
  'editorBracketPairGuide.background1': p.blue.dim + '38',
  'editorBracketPairGuide.background2': p.violet.dim + '38',
  'editorBracketPairGuide.background3': p.teal.mid + '38',
  'editorBracketPairGuide.background4': p.green.dim + '38',
  'editorBracketPairGuide.background5': p.sand.dim + '38',
  'editorBracketPairGuide.background6': p.orange + '38',
  'editorBracketPairGuide.activeBackground1': p.blue.dim + '99',
  'editorBracketPairGuide.activeBackground2': p.violet.dim + '99',
  'editorBracketPairGuide.activeBackground3': p.teal.mid + '99',
  'editorBracketPairGuide.activeBackground4': p.green.dim + '99',
  'editorBracketPairGuide.activeBackground5': p.sand.dim + '99',
  'editorBracketPairGuide.activeBackground6': p.orange + '99',
  'editorBracketMatch.background': p.ui.selection + '40',
  'editorBracketMatch.border': p.violet.mid,

  // Diagnostics.
  'editorError.foreground': p.diag.error,
  'editorError.border': '#00000000',
  'editorWarning.foreground': p.diag.warning,
  'editorWarning.border': '#00000000',
  'editorInfo.foreground': p.blue.mid,
  'editorHint.foreground': p.teal.mid,
  'editorUnnecessaryCode.opacity': '#000000aa',

  // Gutter.
  'editorGutter.background': p.vscode.bg,
  'editorGutter.addedBackground': p.vcs.added,
  'editorGutter.modifiedBackground': p.vcs.modified,
  'editorGutter.deletedBackground': p.vcs.deleted,
  'editorGutter.commentRangeForeground': p.base.chromeMid,

  // Inlay hints.
  'editorInlayHint.foreground': p.base.inlayHint,
  'editorInlayHint.background': '#00000000',
  'editorInlayHint.typeForeground': p.base.inlayHint,
  'editorInlayHint.parameterForeground': p.base.inlayHint,

  // Code lens and sticky scroll.
  'editorCodeLens.foreground': p.base.inlayHint,
  'editorStickyScroll.background': p.vscode.titleBar,
  'editorStickyScrollHover.background': '#1a1d30',

  // Overview ruler.
  'editorOverviewRuler.border': p.base.chromeDim,
  'editorOverviewRuler.addedForeground': p.vcs.added,
  'editorOverviewRuler.modifiedForeground': p.vcs.modified,
  'editorOverviewRuler.deletedForeground': p.vcs.deleted,
  'editorOverviewRuler.errorForeground': p.diag.error,
  'editorOverviewRuler.warningForeground': p.diag.warning,
  'editorOverviewRuler.infoForeground': p.blue.mid,
  'editorOverviewRuler.findMatchForeground': p.violet.mid + '80',
  'editorOverviewRuler.selectionHighlightForeground': p.ui.selection,
  'editorOverviewRuler.wordHighlightForeground': p.blue.mid + '80',
  'editorOverviewRuler.bracketMatchForeground': p.violet.mid,

  // Widgets.
  'editorWidget.background': p.ui.popupBg,
  'editorWidget.foreground': p.base.text,
  'editorWidget.border': p.base.chromeMid,
  'editorWidget.resizeBorder': p.violet.mid,
  'editorSuggestWidget.background': p.ui.popupBg,
  'editorSuggestWidget.foreground': p.base.text,
  'editorSuggestWidget.border': p.base.chromeMid,
  'editorSuggestWidget.highlightForeground': p.violet.mid,
  'editorSuggestWidget.focusHighlightForeground': p.violet.bright,
  'editorSuggestWidget.selectedBackground': p.ui.selection,
  'editorSuggestWidget.selectedForeground': p.base.text,
  'editorSuggestWidgetStatus.foreground': p.base.inlayHint,
  'editorHoverWidget.background': p.ui.popupBg,
  'editorHoverWidget.foreground': p.base.text,
  'editorHoverWidget.border': p.base.chromeMid,
  'editorHoverWidget.statusBarBackground': p.vscode.titleBar,
  'peekView.border': p.violet.mid,
  'peekViewEditor.background': p.ui.popupBg,
  'peekViewEditor.matchHighlightBackground': p.violet.mid + '40',
  'peekViewEditorGutter.background': p.ui.popupBg,
  'peekViewResult.background': p.vscode.tabBar,
  'peekViewResult.fileForeground': p.base.text,
  'peekViewResult.lineForeground': p.blue.mid,
  'peekViewResult.matchHighlightBackground': p.violet.mid + '40',
  'peekViewResult.selectionBackground': p.ui.selection,
  'peekViewResult.selectionForeground': p.base.text,
  'peekViewTitle.background': p.ui.popupBg,
  'peekViewTitleDescription.foreground': p.base.inlayHint,
  'peekViewTitleLabel.foreground': p.base.text,

  // Editor groups and tabs.
  'editorGroup.border': p.base.chromeDim,
  'editorGroup.focusedEmptyBorder': p.violet.mid,
  'editorGroup.dropBackground': p.ui.selection + '40',
  'editorGroupHeader.tabsBackground': p.vscode.tabBar,
  'editorGroupHeader.tabsBorder': p.base.chromeDim,
  'editorGroupHeader.noTabsBackground': p.vscode.bg,
  'tab.activeBackground': p.vscode.bg,
  'tab.activeForeground': p.base.text,
  'tab.activeBorder': '#00000000',
  'tab.activeBorderTop': p.violet.mid,
  'tab.inactiveBackground': p.vscode.tabBar,
  'tab.inactiveForeground': p.base.inlayHint,
  'tab.border': p.base.chromeDim,
  'tab.hoverBackground': p.vscode.bg,
  'tab.hoverForeground': p.base.text,
  'tab.unfocusedActiveBackground': p.vscode.bg,
  'tab.unfocusedActiveForeground': '#8f96b3',
  'tab.unfocusedActiveBorderTop': p.base.chromeMid,
  'tab.unfocusedInactiveBackground': p.vscode.tabBar,
  'tab.unfocusedInactiveForeground': p.base.chromeMid,
  'tab.lastPinnedBorder': p.base.chromeMid,

  // Activity bar and sidebar.
  'activityBar.background': p.vscode.titleBar,
  'activityBar.foreground': p.base.text,
  'activityBar.inactiveForeground': p.base.chromeMid,
  'activityBar.border': p.base.chromeDim,
  'activityBar.activeBorder': p.violet.mid,
  'activityBar.activeBackground': p.ui.selection + '40',
  'activityBarBadge.background': p.violet.mid,
  'activityBarBadge.foreground': p.vscode.bg,
  'sideBar.background': '#1a1d2e',
  'sideBar.foreground': p.base.text,
  'sideBar.border': p.base.chromeDim,
  'sideBarTitle.foreground': p.base.inlayHint,
  'sideBarSectionHeader.background': '#1a1d2e',
  'sideBarSectionHeader.foreground': p.base.text,
  'sideBarSectionHeader.border': p.base.chromeDim,

  // Lists.
  'list.activeSelectionBackground': p.ui.selection,
  'list.activeSelectionForeground': p.base.text,
  'list.inactiveSelectionBackground': p.base.chromeDim,
  'list.inactiveSelectionForeground': p.base.text,
  'list.hoverBackground': p.base.chromeDim + '60',
  'list.hoverForeground': p.base.text,
  'list.focusBackground': p.ui.selection,
  'list.focusForeground': p.base.text,
  'list.focusOutline': p.violet.mid,
  'list.highlightForeground': p.violet.mid,
  'list.dropBackground': p.ui.selection + '40',
  'list.errorForeground': p.diag.error,
  'list.warningForeground': p.diag.warning,
  'list.deemphasizedForeground': p.base.inlayHint,
  'listFilterWidget.background': p.ui.popupBg,
  'listFilterWidget.outline': p.violet.mid,
  'listFilterWidget.noMatchesOutline': p.diag.error,

  // Status and title bars.
  'statusBar.background': p.ui.selection,
  'statusBar.foreground': p.base.text,
  'statusBar.border': '#00000000',
  'statusBar.noFolderBackground': p.base.chromeDim,
  'statusBar.noFolderForeground': p.base.text,
  'statusBar.debuggingBackground': p.orange,
  'statusBar.debuggingForeground': p.vscode.bg,
  'statusBarItem.remoteBackground': p.teal.mid,
  'statusBarItem.remoteForeground': p.vscode.bg,
  'statusBarItem.hoverBackground': '#ffffff20',
  'statusBarItem.activeBackground': '#ffffff30',
  'titleBar.activeBackground': p.vscode.titleBar,
  'titleBar.activeForeground': p.base.text,
  'titleBar.inactiveBackground': p.vscode.titleBar,
  'titleBar.inactiveForeground': p.base.inlayHint,
  'titleBar.border': p.base.chromeDim,

  // Inputs and controls.
  'input.background': p.base.chromeDim,
  'input.foreground': p.base.text,
  'input.border': p.base.chromeMid,
  'input.placeholderForeground': p.base.inlayHint,
  'inputOption.activeBackground': p.ui.selection,
  'inputOption.activeForeground': p.base.text,
  'inputOption.activeBorder': p.violet.mid,
  'inputValidation.errorBackground': p.diag.error + '40',
  'inputValidation.errorBorder': p.diag.error,
  'inputValidation.warningBackground': p.diag.warning + '40',
  'inputValidation.warningBorder': p.diag.warning,
  'inputValidation.infoBackground': p.blue.mid + '40',
  'inputValidation.infoBorder': p.blue.mid,
  'dropdown.background': p.base.chromeDim,
  'dropdown.foreground': p.base.text,
  'dropdown.border': p.base.chromeMid,
  'dropdown.listBackground': p.ui.popupBg,
  'button.background': p.violet.mid,
  'button.foreground': p.vscode.bg,
  'button.hoverBackground': p.violet.bright,
  'button.secondaryBackground': p.ui.selection,
  'button.secondaryForeground': p.base.text,
  'button.secondaryHoverBackground': p.base.chromeMid,
  'checkbox.background': p.base.chromeDim,
  'checkbox.foreground': p.base.text,
  'checkbox.border': p.base.chromeMid,

  // Scrollbar and notifications.
  'scrollbar.shadow': '#00000040',
  'scrollbarSlider.background': p.blue.dim + '40',
  'scrollbarSlider.hoverBackground': p.blue.bright + '80',
  'scrollbarSlider.activeBackground': p.blue.bright,
  'notifications.background': '#1e2138',
  'notifications.foreground': p.base.text,
  'notifications.border': p.base.chromeMid,
  'notificationsErrorIcon.foreground': p.diag.error,
  'notificationsWarningIcon.foreground': p.diag.warning,
  'notificationsInfoIcon.foreground': p.blue.mid,

  // Panel and terminal.
  'panel.background': p.vscode.bg,
  'panel.border': p.base.chromeMid,
  'panelTitle.activeBorder': p.violet.mid,
  'panelTitle.activeForeground': p.base.text,
  'panelTitle.inactiveForeground': p.base.inlayHint,
  'panelSectionHeader.background': p.vscode.tabBar,
  'panelSectionHeader.foreground': p.base.text,
  'terminal.background': p.vscode.bg,
  'terminal.foreground': p.base.text,
  'terminal.selectionBackground': p.ui.selection,
  'terminal.inactiveSelectionBackground': p.ui.selection + '80',
  'terminal.border': p.base.chromeMid,
  'terminal.tab.activeBorder': p.violet.mid,
  'terminalCursor.foreground': p.base.text,
  'terminalCursor.background': p.vscode.bg,
  'terminal.ansiBlack': p.base.chromeDim,
  'terminal.ansiBrightBlack': p.base.chromeMid,
  'terminal.ansiRed': p.diag.error,
  'terminal.ansiBrightRed': p.diag.error,
  'terminal.ansiGreen': p.green.mid,
  'terminal.ansiBrightGreen': p.green.bright,
  'terminal.ansiYellow': p.sand.mid,
  'terminal.ansiBrightYellow': p.sand.bright,
  'terminal.ansiBlue': p.blue.mid,
  'terminal.ansiBrightBlue': p.blue.bright,
  'terminal.ansiMagenta': p.violet.mid,
  'terminal.ansiBrightMagenta': p.violet.bright,
  'terminal.ansiCyan': p.teal.mid,
  'terminal.ansiBrightCyan': p.teal.bright,
  'terminal.ansiWhite': p.base.text,
  'terminal.ansiBrightWhite': '#ffffff',

  // Git decorations and minimap.
  'gitDecoration.addedResourceForeground': p.vcs.added,
  'gitDecoration.modifiedResourceForeground': p.vcs.modified,
  'gitDecoration.deletedResourceForeground': p.vcs.deleted,
  'gitDecoration.renamedResourceForeground': p.teal.mid,
  'gitDecoration.untrackedResourceForeground': p.green.bright,
  'gitDecoration.ignoredResourceForeground': p.base.chromeMid,
  'gitDecoration.conflictingResourceForeground': p.orange,
  'gitDecoration.stageModifiedResourceForeground': p.vcs.modified,
  'gitDecoration.stageDeletedResourceForeground': p.vcs.deleted,
  'submoduleResourceForeground': p.blue.mid,
  'minimap.findMatchHighlight': p.violet.mid + '80',
  'minimap.selectionHighlight': p.ui.selection,
  'minimap.errorHighlight': p.diag.error,
  'minimap.warningHighlight': p.diag.warning,
  'minimapGutter.addedBackground': p.vcs.added,
  'minimapGutter.modifiedBackground': p.vcs.modified,
  'minimapGutter.deletedBackground': p.vcs.deleted,
  'minimapSlider.background': p.blue.dim + '20',
  'minimapSlider.hoverBackground': p.blue.dim + '40',
  'minimapSlider.activeBackground': p.blue.dim + '60',

  // Diff editor.
  'diffEditor.insertedTextBackground': p.vcs.added + '20',
  'diffEditor.removedTextBackground': p.vcs.deleted + '20',
  'diffEditor.insertedLineBackground': p.vcs.added + '15',
  'diffEditor.removedLineBackground': p.vcs.deleted + '15',
  'diffEditor.diagonalFill': p.base.chromeMid,
  'diffEditorGutter.insertedLineBackground': p.vcs.added + '40',
  'diffEditorGutter.removedLineBackground': p.vcs.deleted + '40',

  // Breadcrumbs, quick input, and menus.
  'breadcrumb.foreground': p.base.inlayHint,
  'breadcrumb.background': p.vscode.bg,
  'breadcrumb.focusForeground': p.base.text,
  'breadcrumb.activeSelectionForeground': p.base.text,
  'breadcrumbPicker.background': p.ui.popupBg,
  'quickInput.background': p.ui.popupBg,
  'quickInput.foreground': p.base.text,
  'quickInputTitle.background': p.vscode.tabBar,
  'quickInputList.focusBackground': p.ui.selection,
  'quickInputList.focusForeground': p.base.text,
  'quickInputList.focusIconForeground': p.violet.mid,
  'menu.background': p.ui.popupBg,
  'menu.foreground': p.base.text,
  'menu.selectionBackground': p.ui.selection,
  'menu.selectionForeground': p.base.text,
  'menu.separatorBackground': p.base.chromeMid,
  'menu.border': p.base.chromeMid,
  'menubar.selectionBackground': p.ui.selection,
  'menubar.selectionForeground': p.base.text,

  // Badge, progress, symbols, and misc.
  'badge.background': p.violet.mid,
  'badge.foreground': p.vscode.bg,
  'progressBar.background': p.violet.mid,
  'symbolIcon.classForeground': p.violet.bright,
  'symbolIcon.constantForeground': p.teal.mid,
  'symbolIcon.constructorForeground': p.blue.mid,
  'symbolIcon.enumeratorForeground': p.teal.mid,
  'symbolIcon.enumeratorMemberForeground': p.teal.mid,
  'symbolIcon.functionForeground': p.blue.mid,
  'symbolIcon.interfaceForeground': p.green.mid,
  'symbolIcon.keywordForeground': p.violet.mid,
  'symbolIcon.methodForeground': p.blue.mid,
  'symbolIcon.moduleForeground': p.base.text,
  'symbolIcon.namespaceForeground': p.violet.bright,
  'symbolIcon.numberForeground': p.sand.mid,
  'symbolIcon.operatorForeground': p.orange,
  'symbolIcon.propertyForeground': p.teal.bright,
  'symbolIcon.stringForeground': p.green.bright,
  'symbolIcon.structForeground': p.teal.mid,
  'symbolIcon.typeParameterForeground': p.violet.whisper,
  'symbolIcon.variableForeground': p.base.text,
  'tree.indentGuidesStroke': p.base.chromeDim,
  'focusBorder': p.violet.mid + '80',
  'widget.shadow': '#00000060',
  'selection.background': p.ui.selection,
  'descriptionForeground': p.base.inlayHint,
  'errorForeground': p.diag.error,
  'icon.foreground': p.base.text,
}

// Semantic token colors.
export const semanticTokenColors: Record<string, { foreground: string; fontStyle?: string }> = {
  variable: { foreground: p.base.text },
  'variable.readonly': { foreground: p.teal.mid },
  'variable.readonly.global': { foreground: p.teal.mid },
  parameter: { foreground: p.teal.whisper },
  property: { foreground: p.teal.bright },
  'property.readonly': { foreground: p.teal.mid },
  function: { foreground: p.blue.mid },
  'function.defaultLibrary': { foreground: p.blue.mid },
  method: { foreground: p.blue.mid },
  'method.defaultLibrary': { foreground: p.blue.mid },
  keyword: { foreground: p.violet.mid },
  modifier: { foreground: p.violet.mid },
  type: { foreground: p.violet.bright },
  'type.defaultLibrary': { foreground: p.violet.bright },
  class: { foreground: p.violet.bright },
  'class.defaultLibrary': { foreground: p.violet.bright },
  interface: { foreground: p.green.mid },
  enum: { foreground: p.teal.mid },
  enumMember: { foreground: p.teal.mid },
  struct: { foreground: p.teal.mid },
  typeParameter: { foreground: p.violet.whisper },
  namespace: { foreground: p.violet.bright },
  decorator: { foreground: p.blue.bright },
  annotation: { foreground: p.blue.bright },
  string: { foreground: p.green.bright },
  number: { foreground: p.sand.mid },
  regexp: { foreground: p.green.bright },
  operator: { foreground: p.orange },
  comment: { foreground: p.base.comment, fontStyle: 'italic' },
  'comment.documentation': { foreground: p.base.comment, fontStyle: 'italic' },
  macro: { foreground: p.violet.mid },
  label: { foreground: p.blue.mid },
  boolean: { foreground: p.sand.mid },
  builtinType: { foreground: p.violet.bright },
  escapeSequence: { foreground: p.teal.bright },
  formatSpecifier: { foreground: p.teal.bright },
  selfKeyword: { foreground: p.violet.mid },
  lifetime: { foreground: p.violet.mid },
}

// TextMate token colors.
export const tokenColors = [
  {
    scope: ['comment', 'punctuation.definition.comment', 'comment.block.documentation'],
    settings: { foreground: '#606480', fontStyle: 'italic' },
  },
  {
    scope: [
      'keyword',
      'keyword.control',
      'keyword.other',
      'storage.type',
      'storage.modifier',
      'keyword.operator.new',
      'keyword.operator.delete',
      'keyword.other.unit',
    ],
    settings: { foreground: '#c498ff' },
  },
  {
    scope: [
      'entity.name.type',
      'entity.name.class',
      'entity.other.inherited-class',
      'support.class',
      'support.type',
      'entity.name.type.class',
      'entity.name.namespace',
    ],
    settings: { foreground: '#dbbeff' },
  },
  { scope: 'entity.name.type.interface', settings: { foreground: '#96cc9e' } },
  {
    scope: ['entity.name.function', 'support.function', 'entity.name.method', 'meta.function-call entity.name.function'],
    settings: { foreground: '#8aabe6' },
  },
  { scope: ['variable.parameter', 'meta.function.parameters variable'], settings: { foreground: '#bdd8e8' } },
  { scope: ['variable', 'variable.other', 'variable.other.readwrite'], settings: { foreground: '#c0caf5' } },
  { scope: ['variable.other.constant', 'variable.other.enummember'], settings: { foreground: '#6ec4b6' } },
  { scope: ['variable.other.property', 'support.variable.property', 'meta.property.object'], settings: { foreground: '#8fd4c8' } },
  { scope: ['string', 'string.quoted', 'string.template', 'string.unquoted'], settings: { foreground: '#88dda0' } },
  { scope: ['punctuation.definition.string.begin', 'punctuation.definition.string.end'], settings: { foreground: '#88dda0' } },
  { scope: ['string.regexp', 'constant.regexp'], settings: { foreground: '#88dda0' } },
  { scope: ['constant.character.escape', 'constant.other.placeholder'], settings: { foreground: '#8fd4c8' } },
  { scope: ['punctuation.definition.template-expression', 'punctuation.section.embedded'], settings: { foreground: '#8fd4c8' } },
  {
    scope: [
      'constant.numeric',
      'constant.language.boolean',
      'constant.language.null',
      'constant.language.undefined',
      'constant.language',
      'constant.other',
    ],
    settings: { foreground: '#c5c28a' },
  },
  {
    scope: [
      'keyword.operator',
      'punctuation.accessor',
      'punctuation.separator',
      'punctuation.terminator',
      'punctuation.definition.block',
      'meta.brace',
    ],
    settings: { foreground: '#e09a68' },
  },
  { scope: ['variable.type.parameter', 'entity.name.type.parameter'], settings: { foreground: '#c2c0e8' } },
  {
    scope: ['meta.decorator', 'punctuation.decorator', 'entity.name.function.decorator', 'meta.annotation', 'storage.type.annotation'],
    settings: { foreground: '#a5bcf0' },
  },
  { scope: 'support.type.property-name.css', settings: { foreground: '#8aabe6' } },
  { scope: ['meta.property-value.css', 'support.constant.property-value.css'], settings: { foreground: '#88dda0' } },
  { scope: 'entity.other.attribute-name.class.css', settings: { foreground: '#8fd4c8' } },
  { scope: 'entity.other.attribute-name.id.css', settings: { foreground: '#a5bcf0' } },
  { scope: 'entity.name.tag.css', settings: { foreground: '#dbbeff' } },
  { scope: ['entity.name.tag', 'meta.tag.sgml'], settings: { foreground: '#dbbeff' } },
  { scope: ['entity.other.attribute-name', 'meta.tag.attributes'], settings: { foreground: '#8fd4c8' } },
  {
    scope: ['punctuation.definition.tag', 'punctuation.definition.tag.begin', 'punctuation.definition.tag.end'],
    settings: { foreground: '#e09a68' },
  },
  { scope: 'support.type.property-name.json', settings: { foreground: '#8aabe6' } },
  { scope: 'entity.name.tag.yaml', settings: { foreground: '#8aabe6' } },
  { scope: 'string.unquoted.plain.in.yaml', settings: { foreground: '#88dda0' } },
  {
    scope: ['markup.heading', 'entity.name.section.markdown', 'punctuation.definition.heading'],
    settings: { foreground: '#c498ff', fontStyle: 'bold' },
  },
  { scope: 'markup.bold', settings: { foreground: '#c0caf5', fontStyle: 'bold' } },
  { scope: 'markup.italic', settings: { foreground: '#c0caf5', fontStyle: 'italic' } },
  { scope: ['markup.inline.raw', 'markup.fenced_code.block'], settings: { foreground: '#8fd4c8' } },
  { scope: 'punctuation.definition.list.begin.markdown', settings: { foreground: '#e09a68' } },
  { scope: 'markup.quote', settings: { foreground: '#606480', fontStyle: 'italic' } },
  { scope: ['markup.underline.link', 'meta.link.inline markup.underline.link'], settings: { foreground: '#a5bcf0' } },
  { scope: 'keyword.declaration.dart', settings: { foreground: '#c498ff' } },
  { scope: ['entity.name.type.dart', 'support.class.dart'], settings: { foreground: '#dbbeff' } },
  { scope: ['keyword.other.using.cs', 'keyword.other.namespace.cs'], settings: { foreground: '#c498ff' } },
  { scope: 'entity.name.type.cs', settings: { foreground: '#dbbeff' } },
  { scope: 'entity.other.attribute-name.vue', settings: { foreground: '#8fd4c8' } },
  { scope: 'invalid', settings: { foreground: '#e07891', fontStyle: 'underline' } },
  { scope: 'invalid.deprecated', settings: { foreground: '#c9a55a', fontStyle: 'underline' } },
]
